{% set name = "empyrical-reloaded" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 45b550445a23de07d508e54f686df2e8


build:
  number: 0
  skip: true # [py<37 or not x86_64]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - empyrical

about:
  home: https://empyrical.ml4trading.io
  license: BSD
  summary: 'Common financial risk metrids'
